### ISSUE TITLE
Discussion: non-stable versions

### ISSUE THREAD

**Issue by SupposedlySam** [devmil/dart_apitool#104]
Hello, I was wondering if your tool accounted for changes on a non-stable version?

See https://dev.to/malykhinvi/semver-0-x-x-46e7 for details.

Essentially, 

`(>=1).x.x` follows standard practices `breaking.backwards_compatible_feature.backwards_compatible_fix`
where
`0.x.x` follows `ignored.breaking.backwards_compatible_change`

**Comment by devmil** [comment]
It should behave according to semver.

The package I use (pub_semver) offers a [nextBreaking](https://pub.dev/documentation/pub_semver/latest/pub_semver/Version/nextBreaking.html) property which increases major for >0 major versions and minor for ==0 major versions.
https://github.com/devmil/dart_apitool/blob/6e2f6478e6069c5ea60312cd400d282b952860ba/lib/src/cli/commands/diff_command.dart#L309

**Comment by supposedlysam-bb** [comment]
Thanks!

**Comment by SupposedlySam** [comment]
Thanks!
