### ISSUE TITLE
Dependency updates cause incorrect expected min version

### ISSUE THREAD

**Issue by SupposedlySam** [devmil/dart_apitool#105]
When viewing a patch difference on the `cloud_firestore` package I noticed the expected min version was expected to be `4.4.0` instead of `4.3.2`. However, the only thing the package updated in their changelog was a refactor and some fixes

![image](https://user-images.githubusercontent.com/27933222/218547971-7624b1a6-b5b8-4e2b-b2f1-6ce5195638a6.png)

Looking at the README for Change Codes, it looks like the tool assumes minor version updates to dependencies should mean a minor version update to the package as well. However, I don't believe this is correct.

Although the dependency might have received a new feature, it doesn't mean that feature was passed through to the user. Therefore, a patch update should be the expected version until the public API of the package changes to expose the feature from the dependency. 

## Example
`dart-apitool diff --old pub://cloud_firestore/4.3.1 --new pub://cloud_firestore/4.3.2`

## Output
```bash
Preparing cloud_firestore:4.3.1
Copying sources from /Users/supposedlysam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.1
Preparing cloud_firestore:4.3.2
Copying sources from /Users/supposedlysam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.2
Analyzing /Users/supposedlysam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.1
Analyzing /Users/supposedlysam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-4.3.2
Cleaning up
Cleaning up

No breaking changes!
Non-Breaking changes
├── Package dependency "cloud_firestore_platform_interface" version changed from "^5.10.0" to "^5.10.2" (CD03)
├── Package dependency "cloud_firestore_web" version changed from "^3.2.1" to "^3.2.2" (CD03)
├── Package dependency "firebase_core" version changed from "^2.4.1" to "^2.5.0" (CD03)
└── Package dependency "firebase_core_platform_interface" version changed from "^4.5.2" to "^4.5.3" (CD03)

To learn more about the detected changes visit: https://github.com/devmil/dart_apitool/blob/main/readme/change_codes.md

Checking Package version

Old version: "4.3.1"
Expecting minimum version: "4.4.0" (non-breaking changes)
New Version is too low!
Got "4.3.2" expected >= "4.4.0"
```

## Proposed Change
Update the tool to no longer expect a minor version update to the package when a minor version update is pulled in from a dependency.

**Comment by devmil** [comment]
Yes, that's a valid point. I agree with you that in that case a patch increase would be sufficient.
Currently dart_apitool only differentiates breaking and non-breaking changes but I think it makes sense to distinguish the non-breaking changes more.

Thanks for bringing this up!

**Comment by devmil** [comment]
see referenced PR.
I think any compatible dependency change (remove, add in version range) can lead to a patch-only version bump
