### ISSUE TITLE
Resolve `_FileToAnalyzeEntry` Error

### ISSUE THREAD

**Issue by SupposedlySam** [devmil/dart_apitool#106]
When checking the output of the tool against versions of my own package, I'm met with many `[ERROR] { exception: Problem parsing _FileToAnalyzeEntry(filePath: /src/batch.dart, shownNames: [], hiddenNames: [], exportedBy: {firefuel.dart}): Bad state: Unable to find the context to /src/batch.dart, stacktrace: null }` errors.

## Reproduce
Run `dart-apitool diff --old pub://firefuel/0.3.1 --new pub://firefuel/0.3.2`

## Package Resources
- pub.dev: https://pub.dev/packages/firefuel
- github: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel

## Discussion
Would you advise on whether this is an issue with my package or if it is a bug within the tool?

Thanks!

**Comment by devmil** [comment]
The special case of your package is that it references the parts to export via local package refs. This triggered a bug in dart_apitool.
Thanks for sharing 👍
